### ISSUE TITLE
Docs: Linear interpolation example code is incorrect

### ISSUE THREAD

**Issue by andrewn** [Line-us/Line-us-Programming#1]
There's a small typo in [GCodeSpec.pdf](https://github.com/Line-us/Line-us-Programming/blob/83f1648eef8c85da01c6a267ef5fefb65d2b9a87/Documentation/GCodeSpec.pdf). The Examples for `G01` are `G00 X1200 Y1300 Z1000` and `G00 Z1000`, using the "Rapid positioning" gcode. They should be: `G01 X1200 Y1300 Z1000` and `G01 Z1000`.

It's a small thing but I mistakenly copied them and sent Line-us whizzing around the place. 😄 

I could submit a Pull Request to fix it but I don't have MS Word. 😢

**Comment by robertpoll** [comment]
Well spotted! All fixed now - thanks for letting us know.

…rob
