### ISSUE TITLE
Greetings and consultation from Shenzhen, China

### ISSUE THREAD

**Issue by adilijiang** [Line-us/Line-us-Programming#5]
Hi,
Thank you for sharing, and I am interested in your project. I saw that you have a well-developed development kit Line-us on the Internet, and it is produced in Shenzhen, China. 
I would like to ask if I can buy a development kit from you. Then pay to you via alipay or Taobao. After I bought it, you shipped it to me from Shenzhen, which is more convenient and safe. 
Looking forward to your reply and thank you very much.

Regards.
Adilijiang

**Comment by robertpoll** [comment]
Hi, Yes, you can buy from http://www.line-us.com/shop If you buy through the Webshop we can ship from Shenzhen - please put your address in the order in Chinese. I'll look out for the order and let you know when it ships.

**Comment by adilijiang** [comment]
Hi, robertpoll 
Thank you very much for your reply.

In this case, I would like to ask, can I use other payment methods?
I don't have a credit card to pay for foreign currency, like a visa card.

In addition, if you can ship from Shenzhen, can the courier fee be cheaper? Because in China, the line-us object is generally 20 yuan, about 2 euros. If I submit an order in your online store, it costs nearly 15 euros. This is a bit expensive for me. So when I write the order, can you help me modify the postage, then I pay?

I look forward to your reply, thank you again.

Regards.
Adilijiang

**Comment by robertpoll** [comment]
Hi,

Yes, we can send from Shenzhen and the postage will be a little cheaper. We have to pay a handling fee so it will be more than $2 but will be cheaper than shipping from here. We can accept PayPal or a bank transfer to a UK bank - are either of those possible? If not let me know what you're able to do and we'll see if we can find something that works.

thanks,

...rob

**Comment by adilijiang** [comment]
Thank you for your reply, I think of a friend who has a visa card, I will ask if he can help me pay for it tomorrow. However, the amount automatically generated by the order on your official website is fixed. How can you reduce the amount?

Thanks，
Adilijiang

**Comment by adilijiang** [comment]
The easiest way is that if you have a Chinese friend next to you who uses WeChat or Alipay, then it is most convenient for me to transfer him/her directly.  ^.^

**Comment by robertpoll** [comment]
Hi,

I think using your friends Visa will be the best option as it's not possible to convert Yuan to GBP here. If you could give me your email address, shipping address and phone number I will create an order for you with the reduced postage and send it to you.

many thanks,

..rob

**Comment by adilijiang** [comment]
Ok, then use visa.
What is your email address? I will send you the information （email address, shipping address and phone number） by email. Then you send me the link with the reduced postage.
After I have successfully paid, you send the goods to me. OK？

Thanks，
Adilijiang

**Comment by robertpoll** [comment]
Yes, that's fine - drop me an email at rob@line-us.com. If you're able to pay today we can get it shipped to you on Monday.

**Comment by adilijiang** [comment]
I have already sent you an email, you can take a look, thank you~

**Comment by robertpoll** [comment]
Hi, Just sent you the invoice - let me know if you don't receive it.

**Comment by adilijiang** [comment]
Hi，
The payment has been completed, thank you.
Check it out when you ship it, so I can use it more conveniently.
In addition, I tried to download the line-us app today, the Android version of the phone, it is not easy to download in China, can you send me the line-us install apk package?
