### ISSUE TITLE
iOS and Android code example

### ISSUE THREAD

**Issue by caichunjian520** [Line-us/Line-us-Programming#6]
I gonna purchase line-us. Before purchase I would like to ask is there any code example to build a native iOS or Android app myself to work with line-us.

I had read the code, there is some framework should be import into project. If I write a nodejs project, what I need to do is to import the 'net' module into project.

So if I make an mobile app to work with line-us, I have to import framework or module.

Hope your company can write examples about it.

**Comment by robertpoll** [comment]
Hi, We don't have an iOS or Android example at the moment. I'd probably suggest using the WebSockets interface rather than plain sockets and this looks like quite a good intro for iOS: https://leaks.wanari.com/2017/03/22/websocket-ios/ and this for Android http://fedepaol.github.io/blog/2017/04/30/android-okhttp-and-websockets/

Of course you can still use the plain sockets interface if you prefer.

**Comment by caichunjian520** [comment]
I am now coding the iOS part. After connected to line-us device with Wifi, I tried to initialize the socket with code:
let ws = WebSocket("wss://line-us.local:1337")

(Then open and send data)

but it said "error Network(The operation couldn’t be completed. Operation timed out)" and closed the socket. 

Any solution?

**Comment by robertpoll** [comment]
Hi, try:

let ws = WebSocket("ws://line-us.local:80")

we run the Websocket server on port 80, and it's http weather than https.

**Comment by caichunjian520** [comment]
Finally I successfully connect with the code: 
ws://line-us/local:1337

I am now working on converting iPhone screen's point to line-us point.

But I still find some issues or problems.
1.  It draws really really slowly(almost 1 minute) when received 84 points array(draw a "0") from my app.
2. When drawing, sometime it will buzz without move its arm. Just like it wants to move but get stuck. I don't know why, but I am sure all the points are in drawing area. This issue only appear in my own app.
3. I know when drawing a line, I just need to send 2 points to the machine(fast and smoothly), but as a drawing app, there will be some curve lines, so I have to send every points from app side to machine. Should I decrease some points to get it faster?

**Comment by robertpoll** [comment]
Would it be possible for you to share the code so I could take a look?
