### ISSUE TITLE
Error with connecting line-us.local 1337

### ISSUE THREAD

**Issue by jjangs85** [Line-us/Line-us-Programming#7]
Hi, I bought 2 robot recently.

I tried to run sample python script but it doesn't work.

I connect Line-us to my WIFI, and also connecting computer with same.

I also tried telnet line-us.local 1337 but it can not connecting.

How can I fix it?

**Comment by robertpoll** [comment]
Hi, are you running on Windows? If so you may need to [install bonjour](url
https://support.apple.com/kb/DL999?locale=en_GB). It could also potentially be a firewall issue so you could also try turning off firewall/AV software running on your PC.

**Comment by jjangs85** [comment]
Dear Line-us,

Thanks for your fast reply.
It works well.

Do you have any plan to make a bigger version?

I'm working on Samsung Electronics and I would like to use this small robot
in my company. However drawing area is too small. If coverage of drawing
area is bigger than Galaxy S10 plus, It'll be perfect for us.


Thank you.
Jang.

2019년 3월 22일 (금) 오후 7:04, robertpoll <notifications@github.com>님이 작성:

**Comment by robertpoll** [comment]
We have looked at a bigger version but no concrete plans at the moment.

**Comment by sixclones** [comment]
Hi I've been facing similar issue. Installing Bonjour and disabling firewall doesn't helped. Do you have any ideas how to solve this?
Thx

**Comment by robertpoll** [comment]
Are you trying to connect from Python?

**Comment by sixclones** [comment]
I'm using NodeJS and I tried using `telnet` command (that failed).
I'll try Python and let you know what's going one.
